module.exports = [
  // { user_id: "james123", following_id: "james123" },
  { user_id: "james123", following_id: "yeye123" },
  { user_id: "james123", following_id: "sandles123" },
  { user_id: "james123", following_id: "potter99" },
  // { user_id: "yeye123", following_id: "yeye123" },
  { user_id: "yeye123", following_id: "LH44" },
  { user_id: "yeye123", following_id: "sandles123" },
  { user_id: "yeye123", following_id: "potter99" },
  // { user_id: "potter99", following_id: "potter99" },
  { user_id: "potter99", following_id: "LH44" },
  { user_id: "potter99", following_id: "sandles123" },
  { user_id: "potter99", following_id: "james123" },
  // { user_id: "sandles123", following_id: "sandles123" },
  { user_id: "sandles123", following_id: "LH44" },
  { user_id: "sandles123", following_id: "yeye123" },
  { user_id: "sandles123", following_id: "james123" },
  // { user_id: "LH44", following_id: "LH44" },
  { user_id: "LH44", following_id: "potter99" },
  { user_id: "LH44", following_id: "yeye123" },
  { user_id: "LH44", following_id: "james123" },
];
