module.exports = [
  // { spotify_id: "james123", following_id: "james123" },
  { spotify_id: "james123", following_id: "yeye123" },
  { spotify_id: "james123", following_id: "sandles123" },
  { spotify_id: "james123", following_id: "potter99" },
  // { spotify_id: "yeye123", following_id: "yeye123" },
  { spotify_id: "yeye123", following_id: "LH44" },
  { spotify_id: "yeye123", following_id: "sandles123" },
  { spotify_id: "yeye123", following_id: "potter99" },
  // { spotify_id: "potter99", following_id: "potter99" },
  { spotify_id: "potter99", following_id: "LH44" },
  { spotify_id: "potter99", following_id: "sandles123" },
  { spotify_id: "potter99", following_id: "james123" },
  // { spotify_id: "sandles123", following_id: "sandles123" },
  { spotify_id: "sandles123", following_id: "LH44" },
  { spotify_id: "sandles123", following_id: "yeye123" },
  { spotify_id: "sandles123", following_id: "james123" },
  // { spotify_id: "LH44", following_id: "LH44" },
  { spotify_id: "LH44", following_id: "potter99" },
  { spotify_id: "LH44", following_id: "yeye123" },
  { spotify_id: "LH44", following_id: "james123" },
  { spotify_id: "c18-jdg", following_id: "james123" },
  { spotify_id: "c18-jdg", following_id: "snr-dev" },
  { spotify_id: "c18-jdg", following_id: "yeye123" },
  { spotify_id: "c18-jdg", following_id: "potter99" },
  { spotify_id: "c18-jdg", following_id: "sandles123" },
  { spotify_id: "c18-jdg", following_id: "LH44" },
  // { spotify_id: "c18-jdg", following_id: "c18-jdg" },
  { spotify_id: "snr-dev", following_id: "c18-jdg" },
  // { spotify_id: "snr-dev", following_id: "snr-dev" },
];
